/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IFluentBoard24Filled: typeof import('~icons/fluent/board24-filled')['default']
    IHeroiconsArrowRightOnRectangleSolid: typeof import('~icons/heroicons/arrow-right-on-rectangle-solid')['default']
    IHeroiconsHomeSolid: typeof import('~icons/heroicons/home-solid')['default']
    IHeroiconsPencilSquareSolid: typeof import('~icons/heroicons/pencil-square-solid')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
